services:

  message-handler:
    build: ./messageHandlerService
    command: ["./wait-for-postgres.sh", "postgres", "${POSTGRES_USER}", "${POSTGRES_DB}", "/messageHandler"]
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - kafka

  message-saver:
    build: ./messageSaverService
    command: ["./wait-for-postgres.sh", "postgres", "${POSTGRES_USER}", "${POSTGRES_DB}","/messageSaver"]
    ports:
      - "5001:5002"
    depends_on:
      - postgres
      - kafka

  postgres:
    image: postgres:14.8-alpine3.18
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    restart: unless-stopped

  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: "001"
      KAFKA_CREATE_TOPICS: "${TOPIC_NAME}:3:1"
      HOSTNAME_COMMAND: "docker info | grep ^Name: | cut -d' ' -f 2"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT"
      KAFKA_ADVERTISED_LISTENERS: "INSIDE://:9092,OUTSIDE://${SERVER_IP}:9094"
      KAFKA_LISTENERS: "INSIDE://:9092,OUTSIDE://:9094"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INSIDE"
      KAFKA_LOG_RETENTION_MS: 86400000
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 5000
    depends_on:
      - zookeeper