FROM golang AS builder

WORKDIR /app

RUN apt-get update && apt-get install -y postgresql-client

COPY ./ ./
RUN chmod +x ./wait-for-postgres.sh

RUN CGO_ENABLED=0 GOOS=linux go build -o /messageHandler ./cmd